# All available autoscalers
autoscalers:
  hv_predictive: # Horizontal/vertical+predictive autoscaling
    prediction_window: 300 # Prediction window in seconds
    prediction_percentile: 95 # Percentile for application's load in the prediction window
    algorithm: fcma, baseline # Allocation and transition algorithms
    transition_time_budget: 0 # Approximate time budget for the transition (0 for simple transaction)
    hot_node_scale_up: False
  
# Select autoscaler
autoscaler: hv_predictive

# Times in seconds for node/container creation/removal
timing_args:
  node_time_to_billing: 20 # Time from the request of creating a node, until it starts to be billed.
  node_creation_time: 100 # Total time from the request of creating a node until the node is ready
                          # to execute containers. A node is billed (node_creation_time - node_time_to_running)
                          # seconds being ready to allocate any container.
  node_removal_time: 10  # Time > 0 from the request of node removal until it is removed. Meanwhile, it is billed.
  container_creation_time: 1 # Time from the request of container creation until it can process load.
  container_removal_time: 5 # Time from the request of container removal until it is removed from the node.
                            # Meanwhile. it can not process new load, but consumes computational resources.
  hot_node_scale_up_time: 60 # Time to hot scale up (upgrade) a node.

# Define applications
apps:
  $A_0$:
    load:
      file: triangle1.csv # Integer load samples in req/s
      time_interval: 60 # Integer time in seconds between two consecutive samples
      repeat: 1 # The whole set of samples in the file is repeated this number of times
      load_offset: 0 # Integer value to be added to every load sample
      load_mult: 1 # Multiplier for the load samples (multiplies also the load offset)
      time_offset: 0 # Advance this number of samples and complete with the last value
    container:
      cpu: 260 mcores
      mem: 0.420 GiB
      perf: 1 req/s
      aggs: [1, 2, 4]
  $A_1$:
    load:
      file: triangle2.csv # Integer load samples in req/s
      time_interval: 60 # Integer time in seconds between two consecutive samples
      repeat: 1 # The whole set of samples in the file is repeated this number of times
      load_offset: 0 # Integer value to be added to every load sample
      load_mult: 1 # Multiplier for the load samples (multiplies also the load offset)
      time_offset: 0 # Advance this number of samples and complete with the last value
    container:
      cpu: 300 mcores
      mem: 0.500 GiB
      perf: 1 req/s
      aggs: [1, 2, 4]

# Simulation time in seconds.
# If application traces are short, the last load in the trace is repeated.
# If application traces are too long, they are truncated at the end.
simulation_time: 3600 # 1 hour